name: Continuous Integration

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  testing:
    runs-on: self-hosted
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Test
        run: bun run test
      - name: Test Build
        run: bun run test:build
      - name: Test Stress
        run: bun run test:stress
        timeout-minutes: 15
