name: Build and Test

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.json'
      - '**/*.jsonc'
      - '**/*.gitignore'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.json'
      - '**/*.jsonc'
      - '**/*.gitignore'

jobs:
  build:
    name: Build and test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Build code
        run: bun run build

      - name: Test
        run: bun run test
