name: Production Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Setup NPM Auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Copy License to Packages
        run: |
          for dir in Packages/*/; do
            cp LICENSE "$dir"
          done
      - name: Remove bun.lock
        run: rm bun.lock
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Publish
        run: bun run release
        env:
          NPM_CONFIG_PROVENANCE: 'true'
      - name: Generate Changelog
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
