name: Release

on:
  push:
    paths:
      - 'Packages/**/package.json'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run changelogithub
        if: github.event.head_commit.message =~ '^chore: release'
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
