name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run changelogithub
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
