name: Release

on:
  push:
    paths:
      - 'Packages/**/package.json'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check commit message
        id: check_commit
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ "$commit_message" == *"chore: release"* ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "Skipping changelog generation: Commit message doesn't contain 'chore: release'"
          fi

      - name: Run changelogithub
        if: steps.check_commit.outputs.should_run == 'true'
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
