name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version from commit
        id: get_version
        run: |
          VERSION=$(git log -1 --pretty=%B | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9\.]+)?')
          echo "Found version: $VERSION"
          echo "::set-output name=VERSION::$VERSION"

      - name: Create Git tag
        uses: actions/github-script@v5
        with:
          script: |
            const tag = '${{ steps.get_version.outputs.VERSION }}'
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            })

      - name: Push tag to origin
        run: |
          git push origin ${{ steps.get_version.outputs.VERSION }}

      - name: Generate changelog
        run: npx changelogithub --to=${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
